apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dbcrul.fullname" . }}-config
data:
  SMTP_ENABLED: "{{ .Values.dbcrul.smtp.enabled }}"
  SMTP_HOST: "{{ .Values.dbcrul.smtp.host }}"
  SMTP_PORT: "{{ .Values.dbcrul.smtp.port }}"
  SMTP_USERNAME: "{{ .Values.dbcrul.smtp.username }}"
  SMTP_SSL_CONNECTION: "{{ .Values.dbcrul.smtp.ssl }}"
  SMTP_VERIFY_SSL_CERTIFICATE: "{{ .Values.dbcrul.smtp.ssl_ver }}"
  SMTP_FROM: "{{ .Values.dbcrul.smtp.from }}"
  PASSWORD_RESET_LINK_PATTERN: "{{ .Values.dbcrul.reset_password_url }}"
  SQL_USERNAME: "{{ tpl .Values.dbcrul.sql.username . }}"
  SQL_DBNAME: "{{ tpl .Values.dbcrul.sql.name . }}"
  SQL_HOST: "{{ tpl .Values.dbcrul.sql.host . }}"
  SQL_PORT: "{{ tpl .Values.dbcrul.sql.port . }}"
