apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "dbcrul.fullname" . }}-secret
data:
  SQL_PASSWORD: {{ tpl .Values.dbcrul.sql.password . | b64enc | quote }}
  SMTP_PASSWORD: {{ tpl .Values.dbcrul.smtp.password . | b64enc | quote }}
