version: '3'
services:
  dbcrul:
    image: 'softwaremill/dbcrul:latest'
    ports:
      - '8080:8080'
    depends_on:
      - dbcrul-db
      - dbcrul-mailhog
    environment:
      SQL_USERNAME: 'postgres'
      SQL_PASSWORD: 'b00t200k4'
      SQL_DBNAME: 'dbcrul'
      SQL_HOST: 'dbcrul-db'
      SQL_PORT: '5432'
      API_HOST: '0.0.0.0'
      SMTP_ENABLED: 'true'
      SMTP_HOST: 'dbcrul-mailhog'
      SMTP_PORT: '1025'
  dbcrul-db:
    image: 'postgres'
    ports:
      - '25432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'b00t200k4'
      POSTGRES_DB: 'dbcrul'
  dbcrul-mailhog:
    image: 'mailhog/mailhog'
    ports:
      - '11025:1025'
      - '18025:8025'

